
[2019-07-24 10:35:18] Traceback (most recent call last):
  File "kivy\properties.pyx", line 860, in kivy.properties.ObservableDict.__getattr__
KeyError: 'scr_mngr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Jeandre Botha/Google Drive/UP/COS301/Interfaces_v2/main.py", line 68, in <module>
    LoginApp().run()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "C:\Users\Jeandre Botha\Google Drive\UP\COS301\Interfaces_v2\kivymd\list.py", line 411, in on_touch_up
    super(BaseListItem, self).on_touch_up(touch)
  File "C:\Users\Jeandre Botha\Google Drive\UP\COS301\Interfaces_v2\kivymd\ripplebehavior.py", line 68, in on_touch_up
    return super(CommonRipple, self).on_touch_up(touch)
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
  File "D:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "C:\Users\Jeandre Botha\Google Drive\UP\COS301\Interfaces_v2\home.kv", line 42, in <module>
    on_release: app.root.get_screen('home').ids.scr_mngr.current = 'user_window'
  File "kivy\properties.pyx", line 863, in kivy.properties.ObservableDict.__getattr__
AttributeError: 'super' object has no attribute '__getattr__'


[2019-08-16 09:22:57] Traceback (most recent call last):
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 100, in <module>
    LoginApp().run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 829, in run
    root = self.build()
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 46, in build
    self.cef.Initialize()
AttributeError: 'LoginApp' object has no attribute 'cef'


[2019-08-16 09:26:19] Traceback (most recent call last):
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 99, in <module>
    LoginApp().run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 342, in idle
    self.dispatch_input()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 327, in dispatch_input
    post_dispatch_input(*pop(0))
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 293, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "F:\Documents\UP\COS301\capstone\Defendr\src\Interfaces_v2\kivymd\list.py", line 411, in on_touch_up
    super(BaseListItem, self).on_touch_up(touch)
  File "F:\Documents\UP\COS301\capstone\Defendr\src\Interfaces_v2\kivymd\ripplebehavior.py", line 68, in on_touch_up
    return super(CommonRipple, self).on_touch_up(touch)
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "F:\Documents\UP\COS301\capstone\Defendr\src\Interfaces_v2\nav_drawer.kv", line 18, in <module>
    on_release: app.load_website('https://www.google.com/','System Metrics')
  File "F:/Documents/UP/COS301/capstone/Defendr/src/Interfaces_v2/main.py", line 87, in load_website
    self.chromium.CreateBrowserSync(url=web_url,
AttributeError: 'bool' object has no attribute 'CreateBrowserSync'


[2019-08-19 14:53:05] Traceback (most recent call last):
  File "main.py", line 29, in <module>
    class LoginApp(App):
  File "main.py", line 43, in LoginApp
    Metrics.start()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 27, in start
    subprocess.Popen('./node_exporter', cwd='Metrics/node_exporter')
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Metrics/node_exporter': 'Metrics/node_exporter'


[2019-08-19 14:55:25] Traceback (most recent call last):
  File "main.py", line 29, in <module>
    class LoginApp(App):
  File "main.py", line 43, in LoginApp
    Metrics.start()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 27, in start
    subprocess.Popen('./node_exporter', cwd='Metrics/node_exporter')
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Metrics/node_exporter': 'Metrics/node_exporter'


[2019-08-22 02:29:43] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 70, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 02:35:18] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 69, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 03:04:38] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 67, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 03:06:29] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 67, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 03:18:20] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 67, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 03:42:58] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 67, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 03:46:15] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 67, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 03:50:40] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 67, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 03:56:38] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 67, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 04:30:57] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 60, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'


[2019-08-22 09:20:27] Traceback (most recent call last):
  File "/usr/lib/python3.6/smtplib.py", line 387, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 829, in run
    root = self.build()
  File "main.py", line 51, in build
    self.manager.add_widget(Login(name='login'))
  File "/usr/lib/python3/dist-packages/kivy/uix/screenmanager.py", line 992, in add_widget
    self.current = screen.name
  File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
  File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
  File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
  File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
  File "/usr/lib/python3/dist-packages/kivy/uix/screenmanager.py", line 1054, in on_current
    screen.dispatch('on_pre_enter')
  File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
  File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
  File "/usr/lib/python3/dist-packages/kivy/lang/builder.py", line 64, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/login.kv", line 6, in <module>
    on_pre_enter: root.connect()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/login.py", line 30, in connect
    facade = FacadeClass()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Facade.py", line 19, in __init__
    self.smpt_connects = self.smpt.connectToSMTPserver()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/emailSender.py", line 32, in connectToSMTPserver
    server = smtplib.SMTP('mail.darknites.co.za', 587 )
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 338, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.6/smtplib.py", line 391, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: [Errno 104] Connection reset by peer


[2019-08-28 13:31:46] Traceback (most recent call last):
  File "main.py", line 103, in <module>
    LoginApp().run()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 856, in run
    self.stop()
  File "/usr/lib/python3/dist-packages/kivy/app.py", line 864, in stop
    self.dispatch('on_stop')
  File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
  File "main.py", line 47, in on_stop
    Metrics.stop()
  File "/home/sisa/Documents/COS301/Defendr/src/Interfaces_v2/Metrics.py", line 60, in stop
    thread.stop()
AttributeError: 'Thread' object has no attribute 'stop'

